@TennisCourt_HostAddress = http://localhost:5189

@USERS_CONTROLLER = users
@COURTS_CONTROLLER = courts
@Test_Id = 019fb33f-739b-7ab6-9a6c-f4a5a9709b5d
GET {{TennisCourt_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{TennisCourt_HostAddress}}/{{USERS_CONTROLLER}}
Content-Type: application/json

{
    "email":"test@test.com",
    "Telephone":"375001234567",
    "name":"Albert"
}

###
GET {{TennisCourt_HostAddress}}/{{USERS_CONTROLLER}}/{{Test_Id}}
Content-Type: application/json

###
GET {{TennisCourt_HostAddress}}/{{COURTS_CONTROLLER}}
Accept: application/json

###
GET {{TennisCourt_HostAddress}}/{{COURTS_CONTROLLER}}/019fcec4-b961-7b16-87f7-8cd761c0b326
Content-Type: application/json

###
POST {{TennisCourt_HostAddress}}/{{COURTS_CONTROLLER}}
Content-Type: application/json

{
    "street":"ul. leninskaya 5",
    "name":"test",
    "surfaceType":"flat",
    "isIndoor":false
}